### ISSUE TITLE
Alpha/Beta/RC releases fail because of there is no incrementation of `preversion` variable

### ISSUE THREAD

**Issue by DRITE** [christian-draeger/bump-semantic-version#4]
It seems there is bug in version `1.0.1`.
If use `action` like this
```
      - name: Bump release version
        id: bump_version2
        uses: christian-draeger/increment-semantic-version@1.0.1
        with:
          current-version: '1.15.2-alpha4'
          version-fragment: 'alpha'
```
then result will be:
```
Run christian-draeger/increment-semantic-version@1.0.1
  with:
    current-version: 1.15.2-alpha4
    version-fragment: alpha
create alpha-release version: 1.15.2-alpha4 -> 1.15.2-alpha1
```
The same for `beta` and `rc`
